export enum NodeType {
    Document = 'document',
    Frontmatter = 'frontmatter',
    Heading = 'heading',
    Paragraph = 'paragraph',
    Hr = 'hr',
    Image = 'image',
    Fence = 'fence',
    Blockquote = 'blockquote',
    List = 'list',
    Item = 'item',
    Table = 'table',
    Thead = 'thead',
    Tbody = 'tbody',
    Tr = 'tr',
    Td = 'td',
    Inline = 'inline',
    Strong = 'strong',
    Em = 'em',
    S = 's',
    Link = 'link',
    Code = 'code',
    Text = 'text',
    Hardbreak = 'hardbreak',
    Softbreak = 'softbreak',
    Error = 'error',
}